### ISSUE TITLE
lss-0.1.0.0 build is broken

### ISSUE THREAD

**Issue by peti** [dbp/lss#2]
Your Cabal file advertises a dependency on `language-css-attoparsec`, but that package cannot be found on Hackage. As a result, there seems to be no way to build your code. Is that intentional?

**Comment by dbp** [comment]
language-css-attoparsec exists as a fork at https://github.com/dbp/language-css-attoparsec. If you either install it or clone it and add it as a sandbox source (if you are using a sandbox) then this will build.

This is, obviously, somewhat of a problem. I didn't write `language-css-attoparsec`, but did have to fix a bunch of stuff to make it usable. The original author did not publish it, and I've been meaning to (but haven't yet gotten around to trying to) get them to accept my changes and release it; or, failing that, give me the okay to publish it myself. 

Because of that, `lss` should really not be on hackage - it was a mistake; I had forgotten that `language-css-attoparsec` wasn't on hackage when I uploaded it.

**Comment by peti** [comment]
I see. Thank you for the explanation. It might be a good idea to mark the package as deprecated. (The link for that on the server is http://hackage.haskell.org/package/lss/maintain, I believe.)

The same applies to http://hackage.haskell.org/package/snaplet-lss, which depends on `lss` and cannot be built either.

**Comment by dbp** [comment]
Good point. I've just done that.

**Comment by peti** [comment]
Thank you!
